# Generated by Django 2.2.6 on 2020-01-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='lab_specifications')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
