# Generated by Django 2.2.6 on 2020-01-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0002_auto_20200112_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('openDate', models.DateTimeField()),
                ('closeDate', models.DateTimeField()),
                ('projectFiles', models.FileField(upload_to='labs/')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
