# Generated by Django 2.2.6 on 2020-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0004_auto_20200114_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('project_Files', models.FileField(upload_to='slides/')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
