# Generated by Django 2.2.6 on 2020-01-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0005_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='project_Files',
            new_name='lecture_slides',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
    ]
