# Generated by Django 2.2.6 on 2020-01-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0007_slide_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labs',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='project_Files',
            new_name='lab_Files',
        ),
    ]
