# Generated by Django 2.2.6 on 2020-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0008_auto_20200119_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('scriptFile', models.FileField(upload_to='scripts/')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
