# Generated by Django 2.2.6 on 2020-01-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0009_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='scriptFile',
            new_name='script_Files',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='lecture_slides',
            new_name='lecture_Files',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
    ]
