# Generated by Django 2.2.6 on 2020-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0010_auto_20200120_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('assignedStudent_username', models.CharField(max_length=128)),
                ('week_number', models.CharField(max_length=128)),
                ('grade', models.TextField(max_length=2048)),
                ('description', models.TextField(max_length=2048)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
