# Generated by Django 2.2.6 on 2020-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='unzipped_directory',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
