# Generated by Django 2.2.6 on 2020-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0012_lab_unzipped_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='unzipped_directory',
        ),
        migrations.AddField(
            model_name='lab',
            name='_unzipped_directory',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
