# Generated by Django 2.2.6 on 2020-02-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0013_auto_20200213_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='_unzipped_directory',
        ),
    ]
