# Generated by Django 2.2.6 on 2020-02-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0014_remove_lab__unzipped_directory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
