# Generated by Django 2.2.6 on 2020-03-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0015_delete_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='comments',
        ),
    ]
