# Generated by Django 2.2.6 on 2020-03-09 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rfwa', '0017_auto_20200309_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='close_Date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 9, 17, 7, 38, 352496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lab',
            name='open_Date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 9, 17, 7, 38, 352475, tzinfo=utc)),
        ),
    ]
